services:
  kafka-1:
    image: bitnami/kafka:latest
    container_name: kafka-1
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=b3e1a8e45f4b4b2a9b8e1f2d3c4e5f6a
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091
